FROM node:10-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD [ "npm", "run", "docker" ]


# FROM node:10-alpine AS builder

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# RUN npm run build

# FROM node:10-alpine

# WORKDIR /app

# COPY --from=builder /app/dist /app/node_modules ./

# COPY . .

# CMD [ "npm", "run", "docker" ]
