stushopapp:
  name: stushop
  image: 09036229746/stushop
  imageVersion: v2
  environment: 
    DB_URI: mongo-service
    IMG_BASE_URI: http://stushop.kubernetes.phirmware.me
    TOKEN_KEY: Tmx8Y=fEn!A2KF=5cU2#&UaHMJweeUcTSWN5-6pXTUEHpu?Yhv
  resources:
    memory: 128Mi
    cpu: 250m
  replicas: 1
  containerPort: 3000
  containerPortName: stushopport

stushopservice:
  type: LoadBalancer
  port: 80

stushopDB:
  name: stushopdb
  image: mongo
  imageVersion: 4.0.4
  resources:
    memory: 80Mi
    cpu: 125m
  containerPort: 27017
  containerPortName: mongoport

stushopDBService:
  type: NodePort

